plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

base {
    archivesName = "${mod_id}-${minecraft_version}"
}
configurations {
    runtimeClasspath.extendsFrom localRuntime
}
java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

repositories {
    maven { url = "https://jm.gserv.me/repository/maven-public/" }
    maven { url = "https://cursemaven.com" }
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate

    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }

    maven {
        name = "RyanHCode Maven"
        url = "https://maven.ryanhcode.dev/releases"
    }

    maven {
        name = "Illusivec4"
        url = "https://maven.theillusivec4.top/"
    } // Curios

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        url "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
        }
    }
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }

    maven {
        name = "Valkyrien Skies"
        url = "https://maven.valkyrienskies.org"
    }
    flatDir {
        dirs 'lib'
    }

}

neoForge {
    version = neoforge_version
    def modId = project.property('mod_id').toString()

    runs {
        configureEach {
            gameDirectory = file('runs')
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', modId, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${modId}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
    compileOnly("org.joml:joml-primitives:1.10.0")
    compileOnly("maven.modrinth:kotlin-for-forge:${forge_kotlin_version}")
    compileOnly("org.valkyrienskies.core:api:${vs_core_version}") { transitive = false }
    compileOnly("org.valkyrienskies.core:impl:${vs_core_version}"){ transitive = false }
    compileOnly("org.valkyrienskies.core:util:${vs_core_version}"){ transitive = false }
    compileOnly("org.valkyrienskies:valkyrienskies-120-forge:${vs2_version}") {transitive = false}
    compileOnly("curse.maven:create-clockwork-807792:7418660")
    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    localRuntime("com.simibubi.create:create-${minecraft_version}:${create_version}") { transitive = false }
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-common-api:${cc_tweaked_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-core-api:${cc_tweaked_version}")
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cc_tweaked_version}")
    localRuntime("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cc_tweaked_version}")
    compileOnly("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    localRuntime("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    localRuntime("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")
    localRuntime("com.tterrag.registrate:Registrate:${registrate_version}")

    compileOnly("foundry.veil:veil-neoforge-${project.minecraft_version}:${project.veil_version}") {
        exclude group: "maven.modrinth"
    }
    localRuntime("foundry.veil:veil-neoforge-${project.minecraft_version}:${project.veil_version}")
    compileOnly("dev.ryanhcode.sable:sable-neoforge-${minecraft_version}:${sable_version}") {
        exclude group: "foundry.veil"
    }
    localRuntime("dev.ryanhcode.sable:sable-neoforge-${minecraft_version}:${sable_version}")

    //Simulated
    compileOnly("dev.simulated_team.simulated:simulated-neoforge-${minecraft_version}:${simulated_version}")
    localRuntime("dev.simulated_team.simulated:simulated-neoforge-${minecraft_version}:${simulated_version}")

    //offroad
    compileOnly("dev.ryanhcode.offroad:offroad-neoforge-${minecraft_version}:${offroad_version}")
    localRuntime("dev.ryanhcode.offroad:offroad-neoforge-${minecraft_version}:${offroad_version}")

    //Aeronautics
    compileOnly("dev.eriksonn.aeronautics:aeronautics-neoforge-${minecraft_version}:${aeronautics_version}")
    localRuntime("dev.eriksonn.aeronautics:aeronautics-neoforge-${minecraft_version}:${aeronautics_version}")
    implementation "curse.maven:vanishmod-423535:7668159"
    jarJar(api("dev.ryanhcode.sable-companion:sable-companion-common-${minecraft_version}:${sable_companion_version}"))



   // compileOnly files("lib/createbigcannons-5.11.7-mc.1.21.1.jar")
    compileOnly files("lib/create_radar-${create_radar_version}.jar")





    compileOnly "maven.modrinth:create-big-cannons:${cbc_version}"
    runtimeOnly "maven.modrinth:create-big-cannons:${cbc_version}"
    compileOnly "maven.modrinth:rpl:${rpl_version}"
    runtimeOnly "maven.modrinth:rpl:${rpl_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly 'org.spongepowered:mixin:0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    def replaceProperties = [
            version                       : version,
            minecraft_version             : minecraft_version,
            minecraft_version_range       : minecraft_version_range,
            neoforge_version              : neoforge_version,
            neoforge_loader_version_range : neoforge_loader_version_range,
            mod_id                        : mod_id,
            mod_name                      : mod_name,
            mod_author                    : mod_author,
            license                       : license,
            credits                       : credits,
            description                   : project.description ?: description,
            create_version                : create_version,
            create_radar_version          : create_radar_version
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta', '*.mixins.json']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    from(rootProject.file('LICENSE.txt')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_author,
                'Specification-Version'   : version,
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : archiveVersion,
                'Implementation-Vendor'   : mod_author,
                'MixinConfigs'            : 'create_kaboom.mixins.json'
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-Xlint:deprecation')
}
